update archive script

diff --git a/archive b/archive
--- a/archive
+++ b/archive
@@ -13,10 +13,14 @@ else
 	echo "INFO: mkdir $id/"
 	mkdir $id || exit
 fi
-[ -e "$id.c"     ] && mv "$id.c"    "$id/"   || echo "WRONG: Cannot move $id.c into $id/"
-[ -e "$id.cpp"   ] && mv "$id.cpp"  "$id/"   || echo "WRONG: Cannot move $id.cpp into $id/"
-[ -e "$id.cc"    ] && mv "$id.cc"   "$id/"   || echo "WRONG: Cannot move $id.cc into $id/"
-[ -e "$id.in"    ] && mv "$id.in"   "$id/"   || echo "WRONG: Cannot move $id.in into $id/"
-[ -e "$id.out"   ] && mv "$id.out"  "$id/"   || echo "WRONG: Cannot move $id.out into $id/"
-[ -e "poj$id.java" ] && mv "poj$id.java" "$id/"  || echo "WRONG: Cannot move poj$id.java into $id/"
+[ -e "$id.c"     ] && (mv "$id.c"    "$id/"   || echo "WRONG: Cannot move $id.c into $id/")
+[ -e "$id.cpp"   ] && (mv "$id.cpp"  "$id/"   || echo "WRONG: Cannot move $id.cpp into $id/")
+[ -e "$id.cc"    ] && (mv "$id.cc"   "$id/"   || echo "WRONG: Cannot move $id.cc into $id/")
+[ -e "$id.in"    ] && (mv "$id.in"   "$id/"   || echo "WRONG: Cannot move $id.in into $id/")
+[ -e "$id.out"   ] && (mv "$id.out"  "$id/"   || echo "WRONG: Cannot move $id.out into $id/")
+[ -e "poj$id.java" ] && (mv "poj$id.java" "$id/"  || echo "WRONG: Cannot move poj$id.java into $id/")
+git add "$id"
+git status
+read -p "git commit -am '#$id AC'. Ctrl-C to abort."
+git commit -am "#$id AC"
 echo "Done."
